/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_version1_CaptureImage */

#ifndef _Included_com_example_version1_CaptureImage
#define _Included_com_example_version1_CaptureImage
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_version1_CaptureImage_ACTIVITY_START_CAMERA_APP
#define com_example_version1_CaptureImage_ACTIVITY_START_CAMERA_APP 0L
#undef com_example_version1_CaptureImage_STATE_PREVIEW
#define com_example_version1_CaptureImage_STATE_PREVIEW 0L
#undef com_example_version1_CaptureImage_STATE_WAIT_LOCK
#define com_example_version1_CaptureImage_STATE_WAIT_LOCK 1L
#ifdef __cplusplus
}
#endif
#endif
