/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "native-lib.h"
#include <opencv2/core/mat.hpp>
/* Header for class com_example_version1_CaptureImage_ImageSave */

#ifndef _Included_com_example_version1_CaptureImage_ImageSave
#define _Included_com_example_version1_CaptureImage_ImageSave
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_version1_CaptureImage_ImageSave
 * Method:    getvalue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_version1_CaptureImage_00024ImageSave_getvalue
  (JNIEnv*, jobject, jlong inpAddr){
   // Mat &src = *(Mat*)inpAddr;
   // Mat &dst = *(Mat*)outAddr;
    /*jclass cls = env->GetObjectClass(mat);
    jfieldID fieldId = env->GetFieldID(cls, "mymat", "[F");
    jobject objArray = env->GetObjectField (mat, fieldId);
    jfloatArray* fArray = reinterpret_cast<jfloatArray*>(&objArray);
    jsize len = env->GetArrayLength(*fArray);*/
    Mat* inMat = (cv::Mat*) inpAddr;
    cv::Mat image = *inMat;
    PreProcess *ptr_process = new PreProcess(image, 200, 300);
    ptr_process->EdgeProcess();
    ptr_process;
    return ptr_process->action;
};


#ifdef __cplusplus
}
#endif
#endif
