/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native-lib.h"
/* Header for class com_example_version1_CaptureImage_ImageSave */

#ifndef _Included_com_example_version1_CaptureImage_ImageSave
#define _Included_com_example_version1_CaptureImage_ImageSave
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_version1_CaptureImage_ImageSave
 * Method:    getvalue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_version1_CaptureImage_00024ImageSave_getvalue
  (JNIEnv*, jobject, jlong){
/*
    Mat* inMat = (cv::Mat*) inpAddr;
    Mat image = *inMat;
    PreProcess *ptr_process = new PreProcess(image, 200, 300);
    ptr_process->EdgeProcess();
    return ptr_process->action;*/
};
/*JNIEXPORT string JNICALL Java_com_example_version1_CaptureImage_00024ImageSave_getString
        (JNIEnv*, jobject,jlong, jstring){

};*/

// Mat &src = *(Mat*)inpAddr;
// Mat &dst = *(Mat*)outAddr;
/*jclass cls = env->GetObjectClass(mat);
jfieldID fieldId = env->GetFieldID(cls, "mymat", "[F");
jobject objArray = env->GetObjectField (mat, fieldId);
jfloatArray* fArray = reinterpret_cast<jfloatArray*>(&objArray);
jsize len = env->GetArrayLength(*fArray);*/
#ifdef __cplusplus
}
#endif
#endif
